doctrine:
    dbal:
        connections:
            eng_repository_connection:
                driver: pdo_mysql
                host: localhost
                user: root
                password: root
                dbname: ezsylius
                charset: UTF8
                port: '8000'
ezpublish:
    imagemagick:
        enabled: true
        path: /usr/bin/convert
    repositories:
        eng_repository:
            engine: legacy
            connection: eng_repository_connection
    siteaccess:
        default_siteaccess: eng
        list:
            - ezdemo_site
            - eng
            - ezdemo_site_admin
        groups:
            ezdemo_site_group:
                - ezdemo_site
                - eng
                - ezdemo_site_admin
        match:
            URIElement: '1'
    system:
        ezdemo_site_group:
            repository: eng_repository
            languages:
                - eng-US
            var_dir: var/ezdemo_site
        eng:
            session:
                name: eZSESSID
        ezdemo_site_admin:
            legacy_mode: true
        ezdemo_site:
            session:
                name: eZSESSID
stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
