login:
    path:   /login
    defaults:  { _controller: ezpublish.security.controller:loginAction }
login_check:
    path:   /login_check
logout:
    path:   /logout

thank_you_page:
    path:   /checkout/thank-you-page
    defaults:  { _controller: EzSyliusCoreBundle:Checkout:thankYou }

_ezpublishRoutes:
    resource: "@EzPublishCoreBundle/Resources/config/routing/internal.yml"

_ezpublishLegacyRoutes:
    resource: "@EzPublishLegacyBundle/Resources/config/routing.yml"

_ezpublishRestRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix:   %ezpublish_rest.path_prefix%

_ezpublishRestOptionsRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix: %ezpublish_rest.path_prefix%
    type: rest_options

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_sylius:
    resource: "sylius_routing.yml"
    prefix: %ez_sylius.shop_path_prefix%

_ezpublishDemoRoutes:
    resource: "@eZDemoBundle/Resources/config/routing.yml"
