# todo task 4 override sylius cart controller class
sylius_cart:
    classes:
        item:
            controller: EzSylius\Sylius\CoreBundle\Controller\CartItemController


# todo task 6 override product and add checkbox field for bigProducts
sylius_product:
    classes:
        product:
            model: EzSylius\Sylius\CoreBundle\Entity\Product
            form:
                default: EzSylius\Sylius\CoreBundle\Form\Type\ProductType

# todo task 7 override shipping method
sylius_shipping:
    classes:
        shipping_method:
            model: EzSylius\Sylius\CoreBundle\Entity\ShippingMethod
            form: EzSylius\Sylius\CoreBundle\Form\Type\ShippingMethodType

# task 8 shipping method with tax
parameters:
    sylius.listener.order_taxation.class: EzSylius\Bundle\CoreBundle\OrderProcessing\TaxationProcessor