ezpublish:
    system:
        code_camp_frontend_group:
            location_view:
                full:
                    sylius_product:
                        template: NetgenSummerCampBundle:override/full:sylius_product.html.twig
                        controller: netgen.controller.full_view:viewProductLocation
                        match:
                            Identifier\ContentType: sylius_product
                line:
                    sylius_product:
                        template: NetgenSummerCampBundle:override/line:sylius_product.html.twig
                        match:
                            Identifier\ContentType: sylius_product
